### ISSUE TITLE
Extracting cpk files from Danganropa AE

### ISSUE THREAD

**Issue by scj643** [Liquid-S/Danganronpa-Another-Tool#2]
The steam version of Danganronpa AE has it's files packed into a cpk file which isn't useful for this tool

**Comment by scj643** [comment]
http://hcs64.com/vgm_ripping.html has source code for unpacking them
utf_tab is the name of the thing on there site

**Comment by Liquid-S** [comment]
Sorry, but at the moment I'm not going to add it to the DRAT. Maybe I'll do it in the future.
I know, this is not the answer you were hoping for, my apologies.

Anyway, look at this if you want to repack the cpk: https://github.com/s1cp/VitaGuide/wiki#unpacking-the-files
