### ISSUE TITLE
BTX converting DRAE doesnt work

### ISSUE THREAD

**Issue by YokujinKaze** [Liquid-S/Danganronpa-Another-Tool#3]
i tried to convert btx to png with your tool and scarlet tool but none of them seem to work

**Comment by Liquid-S** [comment]
Images from PC are a little different, so Scarlet need an update (my tool use Scarlet).
https://github.com/BlackDragonHunt/Danganronpa-Tools/ BD tools should work.

**Comment by YokujinKaze** [comment]
i tried scarlets tool too but im left with .btx.dec (when scarlet says btx to png conversion)

blackdragonhunts py tools dont seem to work for me

**Comment by YokujinKaze** [comment]
what i found out is that scarlet converts .btx to .dec and in hex it starts with "DDS1DDS |" if one were to remove "DDS1" the file would work as a functional DDS file
