### ISSUE TITLE
Translation not showing up

### ISSUE THREAD

**Issue by JellyNutShell2** [Liquid-S/Danganronpa-Another-Tool#6]
The tool seemingly works fine, I was able to extract, translate, and recompile a wad fine. But when I went in game, none of my translations showed up. Even if I selected English or Japanese, it wouldn't show up. Against the example images advisory, I tried to replace the English and Japanese lines with my translation as well, but that didn't work either. Is there some option in-game I have to check to make it show up?

**Comment by Liquid-S** [comment]
Did you replace the original ".lin" or ".pak" with the translated one before repacking the WAD?
First you need to repack the files you edited, then manually replace the original ones within the WAD folder with the translated ones. Finally, rebuild the WAD and place it the new WAD in the game's folder.

**Comment by JellyNutShell2** [comment]
Going inside the lin folder of the actual wad and not the extracted one, the size of e00_001_000 is 1kb, when my translation is 37 kb. For some reason clicking "Repack. .LIN" isn't actually repacking it?

**Comment by Liquid-S** [comment]
Send me the original LIN, your po and the rebuilded LIN please.
