### ISSUE TITLE
LIN Bytecode Decompilation and Other Modding Functionality

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [Liquid-S/Danganronpa-Another-Tool#7]
Would you welcome pull requests to add features to DRAT that are less translation-focused and more mod-focused?

My first contribution would be the addition of a compiler/decompiler for the scripts attached to LIN files [based on my previous work for a similar format for the PS2 GUST games](https://github.com/Sage-of-Mirrors/Faura). I am happy to contribute this and other modding-related functionality to DRAT if it is acceptable; otherwise, I will just create my own tool.

Thanks!

**Comment by Liquid-S** [comment]
Hi! It would be nice, we could make a new branch for this.
But are you sure about this? Maybe it should better for you to work on Spiral, Spiral is mod-focused and have already a lot of work done https://github.com/UnderMybrella/Spiral

**Comment by Sage-of-Mirrors** [comment]
Ah, I didn't know about that project! I'll just use that instead. Thank you for bringing it up!
